FROM httpd:2.4-alpine

MAINTAINER Stelio Moiane <steliomo@gmail.com>

ADD httpd.conf /usr/local/apache2/conf/httpd.conf

ADD httpd-vhosts.conf /usr/local/apache2/conf/httpd-vhosts.conf

# RUN apk add --update certbot